language: objective-c
before_install:
- gem install cocoapods
script: xctool -project Pod/Pod.xcodeproj -scheme Tests -sdk iphonesimulator build test
podfile: Pod/Podfile
script: xctool -workspace Pod/Pod.xcworkspace -scheme Tests -sdk iphonesimulator build test
